# Cabal 3.x
FROM golang:1.25-alpine

RUN apk add --no-cache ghc cabal git

# Update cabal package list
RUN cabal update

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
