# Swift latest
FROM swift:latest AS swift
FROM golang:1.25-alpine

# Copy Swift from official image
COPY --from=swift /usr /usr

RUN apk add --no-cache git libstdc++

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
