# pnpm 8.x (min tested version)
FROM golang:1.25-alpine

RUN apk add --no-cache nodejs npm git
RUN npm install -g pnpm@8.0.0

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["go", "test", "./...", "-v"]
