# Bun latest
FROM golang:1.25-alpine

RUN apk add --no-cache curl unzip git bash

# Install latest Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:${PATH}"

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
