# cpanm (App::cpanminus)
FROM golang:1.25-alpine

RUN apk add --no-cache perl perl-app-cpanminus git

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
