# Nimble latest (Nim package manager)
FROM golang:1.25-alpine

RUN apk add --no-cache nim nimble git

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
