# Stack latest
FROM haskell:latest AS haskell
FROM golang:1.25-bookworm

# Copy stack from haskell image
COPY --from=haskell /usr/local/bin/stack /usr/local/bin/stack

RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
