# yarn 1.x (classic)
FROM golang:1.25-alpine

RUN apk add --no-cache nodejs npm git
RUN npm install -g yarn@1.22.22

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["go", "test", "./...", "-v"]
