# Poetry latest
FROM golang:1.25-alpine

RUN apk add --no-cache python3 py3-pip git

# Install latest Poetry
RUN pip3 install --break-system-packages poetry

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

CMD ["go", "test", "./...", "-v"]
